# Read the documentation: https://github.com/acseo/TypesenseBundle/blob/master/README.md
acseo_typesense:
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
        # Optional : add prefix to all collection names in Typesense
        #collection_prefix: 'app_'
    # Collection settings
    collections:
        entreprises:                                     # Typesense collection name
                entity: 'App\Entity\Entreprise'              # Doctrine Entity class
                fields:
                    #
                    # Keeping Database and Typesense synchronized with ids
                    #
                    id:                                # Entity attribute name
                        name: id                       # Typesense attribute name
                        type: primary                  # Attribute type
                    #
                    # Using again id as a sortable field (int32 required)
                    #
                    sortable_id:
                        entity_attribute: id             # Entity attribute name forced
                        name: sortable_id                # Typesense field name
                        type: int32
                    capitalSocial:
                        name: capitalSocial
                        type: string
                    formeJuridique:
                        name: formeJuridique
                        type: string
                    pointVentes:
                        name: pointVentes
                        type: collection                 # Convert ArrayCollection to array of strings
                    ville:
                        name: ville
                        type: object                    # Object conversion with __toString()
                    villeName:
                        name: villeName
                        type: string
                        facet: true                      # Declare field as facet (required to use "group_by" query option)
                        entity_attribute: ville.name # Equivalent of $book->getAuthor()->getCountry()
                default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
                symbols_to_index: ['+']
